# Generated by Django 3.2.6 on 2021-10-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointload',
            name='id',
        ),
        migrations.AddField(
            model_name='pointload',
            name='index',
            field=models.IntegerField(default=999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
