# Generated by Django 3.2.6 on 2021-10-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0002_auto_20211017_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointload',
            name='id',
            field=models.BigAutoField(auto_created=True, default=888, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointload',
            name='index',
            field=models.IntegerField(),
        ),
    ]
