# Generated by Django 3.2.6 on 2021-11-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0003_auto_20211017_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='jBeamObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L', models.DecimalField(decimal_places=4, max_digits=8)),
                ('E', models.DecimalField(decimal_places=4, max_digits=10)),
                ('I', models.DecimalField(decimal_places=4, max_digits=10)),
                ('A', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Lcant', models.DecimalField(decimal_places=4, max_digits=8)),
                ('Rcant', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
    ]
