# Generated by Django 3.2.6 on 2021-12-06 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0004_jbeamobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributedLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('startMagnitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('startLocation', models.CharField(max_length=10)),
                ('endMagnitude', models.DecimalField(decimal_places=2, max_digits=8)),
                ('endLocation', models.CharField(max_length=10)),
                ('load_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='beam.loadcase')),
            ],
        ),
    ]
