# Generated by Django 3.2.6 on 2022-01-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0007_rename_location_pointload_startlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Ixx', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
