# Generated by Django 3.2.6 on 2022-01-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam', '0008_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('location', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
            ],
        ),
    ]
